/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/album` | `/album`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/profile/about`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile/help`; params?: Router.UnknownInputParams; } | { pathname: `/profile/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/add-edit`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/complete`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/incoming-call`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/video-call`; params?: Router.UnknownInputParams; } | { pathname: `/vision-board/upload`; params?: Router.UnknownInputParams; } | { pathname: `/weekly/questionnaire`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/album` | `/album`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/about`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/help`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `/sessions/add-edit`; params?: Router.UnknownOutputParams; } | { pathname: `/sessions/complete`; params?: Router.UnknownOutputParams; } | { pathname: `/sessions/incoming-call`; params?: Router.UnknownOutputParams; } | { pathname: `/sessions/video-call`; params?: Router.UnknownOutputParams; } | { pathname: `/vision-board/upload`; params?: Router.UnknownOutputParams; } | { pathname: `/weekly/questionnaire`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/album${`?${string}` | `#${string}` | ''}` | `/album${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/auth/onboarding${`?${string}` | `#${string}` | ''}` | `/profile/about${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile/help${`?${string}` | `#${string}` | ''}` | `/profile/subscription${`?${string}` | `#${string}` | ''}` | `/sessions/add-edit${`?${string}` | `#${string}` | ''}` | `/sessions/complete${`?${string}` | `#${string}` | ''}` | `/sessions/incoming-call${`?${string}` | `#${string}` | ''}` | `/sessions/video-call${`?${string}` | `#${string}` | ''}` | `/vision-board/upload${`?${string}` | `#${string}` | ''}` | `/weekly/questionnaire${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/album` | `/album`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/profile/about`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile/help`; params?: Router.UnknownInputParams; } | { pathname: `/profile/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/add-edit`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/complete`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/incoming-call`; params?: Router.UnknownInputParams; } | { pathname: `/sessions/video-call`; params?: Router.UnknownInputParams; } | { pathname: `/vision-board/upload`; params?: Router.UnknownInputParams; } | { pathname: `/weekly/questionnaire`; params?: Router.UnknownInputParams; };
    }
  }
}
